### PR TITLE
[FLINK-23335] add separate run tasks for Java/Scala exercises and solutions

### PR DESCRIPTION
**Pull request by NicoK**
This allows to quickly run the current state of the exercise or the solution implementation from the command line / IDE.

### CODE REVIEW

**Comment by alpinegizmo** [comment]
The one question I have about this is the java-centric-ness of it. I'm wondering if we ought to be completely ignoring Scala, as this does.

**Comment by NicoK** [comment]
True, let's add these tasks instead:
- `runJavaSolution` and `runScalaSolution`
- `runJavaExercise` and `runScalaExercise` (if enabled)

With that, users without IntelliJ should be able to quickly test their implementations as well.

**Review by alpinegizmo — APPROVED** [review]
Works great!

Will you add something to the README about this?

**Comment by NicoK** [comment]
I actually already did add a section to the `README.md`

**Pull request merged**
