### PR TITLE
[FLINK-23670] Add Scala formatting checks to training exercises

### PR DESCRIPTION
**Pull request by NicoK**
This adds the same Scalastyle checks that the main Flink project is using.

BEWARE: do not merge as is - the `.git-blame-ignore-revs` file needs to be adapted manually!

### CODE REVIEW

**Review by alpinegizmo — COMMENTED** [review]
I've had mixed results with this so far. I'm not convinced.

On the CLI it works okay, but in IntelliJ it doesn't work very well at all. I also tried scalastyleVersion 1.5.0 (the latest), which was better in some ways, and worse in others.

It doesn't appear that these tools have anyone supporting them.

I'm considering approving this but only if we disable/ignore the IntelliJ integration, since it seems to be worse than useless. It complains about random things that make no sense, and if I take its suggestions, then the code has actual problems (instead of the ones it thought it had found).

**Comment by NicoK** [comment]
I took this straight off of https://github.com/apache/flink ... how does it work there?

**Comment by NicoK** [comment]
I just updated the PR to try out [scalafmt](https://scalameta.org/scalafmt/docs/configuration.html) instead because that one integrates well with spotless.

Before I update the description, let's see if this works better.

**Comment by alpinegizmo** [comment]
I think this works okay, and I like having the spotless integration.

**Comment by NicoK** [comment]
@alpinegizmo I just updated the description, please have a second look - before merging, I'll then squash all code commits and separate the formatting commit as mentioned

**Review by alpinegizmo — APPROVED** [review]
Works fine on the command line. I hope we can figure out the intellij integration someday.

**Pull request merged**
